namespace CashFlow.Exception;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the Visual Studio Code Extension PrateekMahendrakar.resxpress
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class ResourceErrorMessages 
{
	private static global::System.Resources.ResourceManager resourceMan;
	[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public ResourceErrorMessages()
	{
	}
	/// <summary>
	///   Returns the cached ResourceManager instance used by this class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Resources.ResourceManager ResourceManager
	{
		get
		{
			if (object.ReferenceEquals(resourceMan, null))
			{
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashFlow.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}
	/// <summary>
	///   Overrides the current thread's CurrentUICulture property for all
	///   resource lookups using this strongly typed resource class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Globalization.CultureInfo Culture { get; set; }
	
	/// <summary>
	/// Looks up a localized string similar to Unknown error..
	/// </summary>
	public static string UNKNOWN_ERROR => ResourceManager.GetString("UNKNOWN_ERROR", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to The title is required..
	/// </summary>
	public static string TITLE_REQUIRED => ResourceManager.GetString("TITLE_REQUIRED", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Payment Type is not valid..
	/// </summary>
	public static string PAYMENT_TYPE_INVALID => ResourceManager.GetString("PAYMENT_TYPE_INVALID", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Expenses cannot be for the future..
	/// </summary>
	public static string EXPENSES_CANNOT_FOR_THE_FUTURE => ResourceManager.GetString("EXPENSES_CANNOT_FOR_THE_FUTURE", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to The amount must be greater than zero..
	/// </summary>
	public static string AMOUNT_MUST_BE_GREATER_THAN_ZERO => ResourceManager.GetString("AMOUNT_MUST_BE_GREATER_THAN_ZERO", Culture);
}
